PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS User ( 
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Username TEXT NOT NULL UNIQUE,
	Email TEXT NOT NULL UNIQUE,
	PasswordHash TEXT NOT NULL,
	CreatedAt TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS Room (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL UNIQUE,
	Capacity INTEGER NOT NULL,
	MaxReservationMinutes INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Equipment (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	Name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS RoomEquipment (
	RoomId INTEGER NOT NULL,
	EquipmentId INTEGER NOT NULL,
	Quantity INTEGER NOT NULL DEFAULT 0,
	FOREIGN KEY (RoomId) REFERENCES Room(Id),
	FOREIGN KEY (EquipmentId) REFERENCES Equipment(Id)
);

CREATE TABLE IF NOT EXISTS Reservation (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	RoomId INTEGER NOT NULL,
	Start TEXT NOT NULL,
	End TEXT NOT NULL,
	Purpose TEXT NOT NULL,
	PersonCount INTEGER NOT NULL,
	BookerId INTEGER NOT NULL,
	Status INTEGER NOT NULL DEFAULT 0,
	CreatedAt TEXT NOT NULL DEFAULT (datetime('now')),
	FOREIGN KEY (RoomId) REFERENCES Room(Id),
	FOREIGN KEY (BookerId) REFERENCES User(Id)
);

CREATE TABLE IF NOT EXISTS ReservationHistory (
	Id INTEGER PRIMARY KEY AUTOINCREMENT,
	ReservationId INTEGER NOT NULL,
	ChangedAt TEXT NOT NULL,
	OldStatus INTEGER NOT NULL,
	NewStatus INTEGER NOT NULL,
	ChangedById INTEGER NOT NULL,
	FOREIGN KEY (ReservationId) REFERENCES Reservation(Id),
	FOREIGN KEY (ChangedById) REFERENCES User(Id)
);